development:
  database: blog_dev
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432

test:
  database: blog_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432

production:
  database: blog_pro
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432